name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde la pestaña "Actions"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Make gradlew executable
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Restore Gradle Wrapper
        working-directory: ./android
        run: gradle wrapper --gradle-version 8.2.1

      - name: Build APKs
        working-directory: ./android
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload APKs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaperemix-apks
          path: android/app/build/outputs/apk/**/*.apk
